/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Izvrsava;
import domen.Klijent;
import domen.Zahtev;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author djurd
 */
public class FrmPretragaZahteva extends javax.swing.JDialog {

    Klijent klijent;

    /**
     * Creates new form FrmPretazivanjeZahteva
     */
    public FrmPretragaZahteva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
    }

    public FrmPretragaZahteva(GlavnaForma gf, boolean b, Klijent k) throws InterruptedException {
        this(gf, b);
        this.klijent = k;
        srediPodatke(k);
        srediTabelu(new Zahtev(-1, null, null, 0.0, klijent, null, null));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPretragaZahteva = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZahtevi = new javax.swing.JTable();
        btnObriši = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnPretrazite = new javax.swing.JButton();
        panelKlijent = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOsoba = new javax.swing.JTextField();
        txtKompanija = new javax.swing.JTextField();
        txtKlijentID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBrojTelefona = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtGrad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPretragaZahteva.setBackground(new java.awt.Color(0, 153, 255));
        panelPretragaZahteva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretraga zahteva", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 2, 18))); // NOI18N

        tblZahtevi.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tblZahtevi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZahtevi);

        btnObriši.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnObriši.setText("Obrisi zahtev");
        btnObriši.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrišiActionPerformed(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnIzmeni.setText("Izmeni zahtev");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnNazad.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnDodaj.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnDodaj.setText("Dodaj zahtev");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Pretražite zahtev (ukupna cena) :");

        btnPretrazite.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnPretrazite.setText("Pretraži");
        btnPretrazite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPretragaZahtevaLayout = new javax.swing.GroupLayout(panelPretragaZahteva);
        panelPretragaZahteva.setLayout(panelPretragaZahtevaLayout);
        panelPretragaZahtevaLayout.setHorizontalGroup(
            panelPretragaZahtevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretragaZahtevaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPretragaZahtevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPretragaZahtevaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(txtPretraga)))
                .addGap(18, 18, 18)
                .addGroup(panelPretragaZahtevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPretrazite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObriši, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPretragaZahtevaLayout.setVerticalGroup(
            panelPretragaZahtevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretragaZahtevaLayout.createSequentialGroup()
                .addGroup(panelPretragaZahtevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazite))
                .addGap(24, 24, 24)
                .addGroup(panelPretragaZahtevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPretragaZahtevaLayout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addGap(37, 37, 37)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnObriši)
                        .addGap(34, 34, 34)
                        .addComponent(btnNazad))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelKlijent.setBackground(new java.awt.Color(0, 153, 255));
        panelKlijent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Klijent", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 2, 18))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("Klijent ID:");

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Kompanija:");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Osoba:");

        txtOsoba.setEnabled(false);

        txtKompanija.setEnabled(false);

        txtKlijentID.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("Grad:");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("Broj telefona:");

        txtBrojTelefona.setEnabled(false);

        txtEmail.setEnabled(false);

        txtGrad.setEnabled(false);

        javax.swing.GroupLayout panelKlijentLayout = new javax.swing.GroupLayout(panelKlijent);
        panelKlijent.setLayout(panelKlijentLayout);
        panelKlijentLayout.setHorizontalGroup(
            panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKlijentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(36, 36, 36)
                .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOsoba)
                    .addComponent(txtKompanija)
                    .addComponent(txtKlijentID, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKlijentLayout.setVerticalGroup(
            panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKlijentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtKlijentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKlijentLayout.createSequentialGroup()
                        .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(panelKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtKompanija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKlijent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPretragaZahteva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPretragaZahteva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        JDialog d= new FrmPretragaKlijenata((Frame) this.getParent(), true);
        d.setVisible(true);
        this.dispose();    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try {

            GlavnaForma gf = (GlavnaForma) this.getParent();
            FrmUnosZahteva fuz = new FrmUnosZahteva(gf, true, klijent);
            JOptionPane.showMessageDialog(null, "Sistem je kreirao novi zahtev!");

            fuz.setVisible(true);
            this.setVisible(false);

            this.dispose();
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da kreira novi zahtev!");

            Logger.getLogger(FrmPretragaZahteva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrišiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrišiActionPerformed
        // TODO add your handling code here:
        if (tblZahtevi.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red u tabeli!");
        } else {
            int odgovor = JOptionPane.showConfirmDialog(null, "Da li stavrno želite da obrišete zahtev?",
                    "Brisanje!", JOptionPane.YES_NO_OPTION);
            if (odgovor == JOptionPane.YES_OPTION) {
                try {
                    ModelTabeleZahtev mtz = (ModelTabeleZahtev) tblZahtevi.getModel();
                    ArrayList<Zahtev> zahtevi = mtz.getLista();
                    Zahtev z = zahtevi.get(tblZahtevi.getSelectedRow());

                    ServerskiOdgovor so = Kontroler.getInstanca().obrisiZahtev(z);
                    if (so.isUspesnost()) {
                        JOptionPane.showMessageDialog(this, "Sistem je obrisao zahtev");
                        srediTabelu(new Zahtev(-1, null, null, 0.0, klijent, null, null));

                    } else {
                        JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise zahtev", "Greška!", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(FrmPretragaZahteva.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                return;
            }

        }
    }//GEN-LAST:event_btnObrišiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            // TODO add your handling code here:
            int red = tblZahtevi.getSelectedRow();
            if (red < 0) {
                JOptionPane.showMessageDialog(null, "Morate selektovati red u tabeli!");
                return;
            }

            ModelTabeleZahtev mtz = (ModelTabeleZahtev) tblZahtevi.getModel();
            ArrayList<Zahtev> zahtevi = mtz.getLista();
            Zahtev zahtev = zahtevi.get(tblZahtevi.getSelectedRow());

            FrmUnosZahteva fuz = new FrmUnosZahteva((GlavnaForma) this.getParent(), true, klijent, zahtev);
            fuz.setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(FrmPretragaZahteva.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPretraziteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziteActionPerformed
        try {
            String kriterijum = txtPretraga.getText().trim();
            if (kriterijum.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sistem na može da nađe zahteve po zadatoj vrednosti!",
                        "Kriterijum pretrage mora biti unet!", JOptionPane.ERROR_MESSAGE);
                srediTabelu(new Zahtev(-1, null, null, 0.0, klijent, null, null));
                return;
            }
            Zahtev z = new Zahtev(-1, null, null, 0.0, klijent, null, null);
            z.setKriterijumPretrage(kriterijum);
            ServerskiOdgovor so = kontroler.Kontroler.getInstanca().ucitajZahteve(z);
            if (so.isUspesnost() == false) {
                JOptionPane.showMessageDialog(null, "Sisitem ne moze da nadje zahteve po zadatoj vrednosti");
            } else {
                ArrayList<Zahtev> lista = (ArrayList<Zahtev>) so.getOdgovor();
                ModelTabeleZahtev mtz = new ModelTabeleZahtev(lista);
                tblZahtevi.setModel(mtz);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaZahteva.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnPretraziteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObriši;
    private javax.swing.JButton btnPretrazite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelKlijent;
    private javax.swing.JPanel panelPretragaZahteva;
    private javax.swing.JTable tblZahtevi;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtKlijentID;
    private javax.swing.JTextField txtKompanija;
    private javax.swing.JTextField txtOsoba;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        setLocationRelativeTo(null);
        setTitle("BG Media");
    }

    private void srediTabelu(Zahtev z) throws InterruptedException {
        z.setKriterijumPretrage("");
        ServerskiOdgovor so = kontroler.Kontroler.getInstanca().ucitajZahteve(z);
        ArrayList<Zahtev> lista = (ArrayList<Zahtev>) so.getOdgovor();
        ModelTabeleZahtev mtz = new ModelTabeleZahtev(lista);
        tblZahtevi.setModel(mtz);
    }

    private void srediPodatke(Klijent k) {
        if (k != null) {
            txtKlijentID.setText(k.getKlijentID() + "");
            txtKompanija.setText(k.getKompanija());
            txtOsoba.setText(k.getOsoba());
            txtGrad.setText(k.getGrad());
            txtEmail.setText(k.getEmail());
            txtBrojTelefona.setText(k.getBrojTelefona());

            txtKlijentID.setEditable(false);
            txtKompanija.setEditable(false);
            txtOsoba.setEditable(false);
            txtGrad.setEditable(false);
            txtEmail.setEditable(false);
            txtBrojTelefona.setEditable(false);

        }

    }

}
