/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Klijent;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import transfer.ServerskiOdgovor;

/**
 *
 * @author djurd
 */
public class FrmUnosKlijenta extends javax.swing.JDialog {

    Klijent zaIzmenu;

    /**
     * Creates new form UnosKlijentaDijalog
     */
    public FrmUnosKlijenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKompanija = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtBrojTelefona = new javax.swing.JTextField();
        txtGrad = new javax.swing.JTextField();
        txtOsoba = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        lblKompanijaError = new javax.swing.JLabel();
        lblGradError = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        lblBrojTelefonaError = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        lblOsobaError = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos klijenta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 2, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Kompanija:");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Osoba:");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("Grad:");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("Broj telefona:");

        txtKompanija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKompanijaActionPerformed(evt);
            }
        });

        txtGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradActionPerformed(evt);
            }
        });

        btnUnesi.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnUnesi.setText("Unesi");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnPonisti.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnPonisti.setText("Poništi");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnIzmeni.setText("Izmeni");
        btnIzmeni.setToolTipText("");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnReset.setText("Resetuj polja ");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOsobaError, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGradError, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtGrad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOsoba, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBrojTelefonaError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                    .addComponent(lblKompanijaError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBrojTelefona, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKompanija, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblKompanijaError))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtKompanija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOsobaError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGradError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmailError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrojTelefonaError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnUnesi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPonisti))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKompanijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKompanijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKompanijaActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        this.setVisible(false);
        this.getParent().setVisible(true);
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            String kompanija = txtKompanija.getText().trim();
            String osoba = txtOsoba.getText().trim();
            String grad = txtGrad.getText().trim();
            String email = txtEmail.getText().trim();
            String telefon = txtBrojTelefona.getText().trim();

            boolean validate = validate(kompanija, osoba, grad, email, telefon);
            if (validate == true) {
                //ne sme da bude isto: ime kompanije, email, broj
                ServerskiOdgovor so1 = kontroler.Kontroler.getInstanca().ucitajKlijente();
                ArrayList<Klijent> listaKlijenata = (ArrayList<Klijent>) so1.getOdgovor();
                for (Klijent k : listaKlijenata) {
                    if (k != null && (k.getKompanija().trim().equalsIgnoreCase(kompanija) || k.getEmail().trim().equalsIgnoreCase(email)
                            && k.getBrojTelefona().trim().equalsIgnoreCase(telefon))) {
                        JOptionPane.showMessageDialog(this, "Klijent " + osoba + ", " + kompanija + " se već nalazi u bazi");
                        isprazniPolja();
                        return;
                    }
                }

                Klijent klijent = new Klijent(-1, kompanija, osoba, grad, email, telefon);
                ServerskiOdgovor so = kontroler.Kontroler.getInstanca().unesiKlijenta(klijent);

                if (so.isUspesnost() == true) {                            
                        JOptionPane.showMessageDialog(null, "Sistem je zapamtio klijenta!");
                       
                } else {
                    JOptionPane.showMessageDialog(null, "Sistem ne može da zapamti klijenta!");
                    return;
                }

                GlavnaForma gf = (GlavnaForma) this.getParent();
                gf.setVisible(true);
                this.setVisible(false);
                this.dispose();

            }

        } catch (InterruptedException ex) {
            Logger.getLogger(FrmUnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            String kompanija = txtKompanija.getText().trim();
            String osoba = txtOsoba.getText().trim();
            String grad = txtGrad.getText().trim();
            String email = txtEmail.getText().trim();
            String telefon = txtBrojTelefona.getText().trim();

            boolean validate = validate(kompanija, osoba, grad, email, telefon);
            if (validate == true) {

                Klijent klijent = new Klijent(zaIzmenu.getKlijentID(), kompanija, osoba, grad, email, telefon);
                ServerskiOdgovor so = kontroler.Kontroler.getInstanca().izmeniKlijenta(klijent);

                if (so.isUspesnost() == true) {
                    JOptionPane.showMessageDialog(this, "Sistem je zapamtio izmenjenog klijenta! ");
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti klijenta!");
                    return;
                }

            }

            //GlavnaForma gf = (GlavnaForma) this.getParent();
            //gf.setVisible(true);
            //this.setVisible(false);
            JDialog fpk = new FrmPretragaKlijenata((GlavnaForma) this.getParent(), true);
            fpk.setVisible(true);
            this.setVisible(false);
        } catch (InterruptedException ex) {
            Logger.getLogger(FrmUnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void txtGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        isprazniPolja();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBrojTelefonaError;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblGradError;
    private javax.swing.JLabel lblKompanijaError;
    private javax.swing.JLabel lblOsobaError;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtKompanija;
    private javax.swing.JTextField txtOsoba;
    // End of variables declaration//GEN-END:variables

    private boolean validate(String kompanija, String osoba, String grad, String email, String telefon) throws InterruptedException {
        String regex = "[a-zA-z .]+";
        String numbers = "^\\+\\d{8,15}$";
        String emailForm = "^(.+)@(.+)$";

        //OBAVEZNA POLJA
        if (kompanija.isEmpty()) {
            lblKompanijaError.setText("Obavezno polje!");
            txtKompanija.setBorder(new LineBorder(Color.red, 2));
        }
        if (osoba.isEmpty()) {
            lblOsobaError.setText("Obavezno polje!");
            txtOsoba.setBorder(new LineBorder(Color.red, 2));
        }
        if (grad.isEmpty()) {
            lblGradError.setText("Obavezno polje!");
            txtGrad.setBorder(new LineBorder(Color.red, 2));
        }
        if (email.isEmpty()) {
            lblEmailError.setText("Obavezno polje!");
            txtEmail.setBorder(new LineBorder(Color.red, 2));
        }
        if (telefon.isEmpty()) {
            lblBrojTelefonaError.setText("Obavezno polje!");
            txtBrojTelefona.setBorder(new LineBorder(Color.red, 2));
            return false;
        }

        //KOMAPANIJA
        if (!kompanija.matches(regex)) {
            JOptionPane.showMessageDialog(this, "Polje kompanija nije popunjeno na pravilan način!");
            return false;
        }

        //OSOBA
        if (!osoba.matches(regex)) {
            JOptionPane.showMessageDialog(this, "Polje osoba nije popunjeno na pravilan način!");
            return false;
        }

        //GRAD
        if (!grad.matches(regex)) {
            JOptionPane.showMessageDialog(this, "Polje grad nije popunjeno na pravilan način!");
            return false;
        }

        //EMAIL - format: xx@xx
        if (!email.matches(emailForm)) {
            JOptionPane.showMessageDialog(this, "Polje email nije popunjeno na pravilan način!");
            return false;
        }

        //TELEFON
        //duzina telefona
        if (telefon.length() < 9 || telefon.length() > 16) {
            JOptionPane.showMessageDialog(this, "Broj telefona mora sadržati 8-15 cifara!");
            return false;
        }

        //plus
        if (telefon.charAt(0) != '+') {
            JOptionPane.showMessageDialog(this, "Broj telefona mora počinjati znakom +!");
            return false;
        }

        if (!telefon.matches(numbers)) {
            JOptionPane.showMessageDialog(this, "Polje broj telefona nije popunjeno na pravilan način!");
            return false;
        }

        return true;
    }

    private void isprazniPolja() {
        txtKompanija.setText("");
        txtOsoba.setText("");
        txtGrad.setText("");
        txtEmail.setText("");
        txtBrojTelefona.setText("");

        txtKompanija.setBorder(new LineBorder(Color.gray, 1));
        txtOsoba.setBorder(new LineBorder(Color.gray, 1));
        txtGrad.setBorder(new LineBorder(Color.gray, 1));
        txtEmail.setBorder(new LineBorder(Color.gray, 1));
        txtBrojTelefona.setBorder(new LineBorder(Color.gray, 1));

    }

    private void srediFormu() {
        setLocationRelativeTo(null);
        setTitle("BG Media");
        btnIzmeni.setEnabled(false);

    }

    public void srediFormuZaIzmenu(Klijent k) {
        this.zaIzmenu = k;
        btnIzmeni.setEnabled(true);
        btnUnesi.setEnabled(false);
        txtKompanija.setText(k.getKompanija());
        txtOsoba.setText(k.getOsoba());
        txtGrad.setText(k.getGrad());
        txtEmail.setText(k.getEmail());
        txtBrojTelefona.setText(k.getBrojTelefona());

    }
}
