/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.Color;
import kontroler.Kontroler;
import niti.PokretanjeServera;

/**
 *
 * @author djurd
 */
public class ServerskaForma extends javax.swing.JFrame {

    PokretanjeServera ps;

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        srediFormu();
        Kontroler.getInstanca().setForma(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblServer = new javax.swing.JLabel();
        btnPodavanjeBaze = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        btnPokreni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pokretanje servera", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 2, 14))); // NOI18N

        lblServer.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        btnPodavanjeBaze.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnPodavanjeBaze.setText("Podešavanje baze");
        btnPodavanjeBaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPodavanjeBazeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblServer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPodavanjeBaze))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPodavanjeBaze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(lblServer))
        );

        btnZaustavi.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnZaustavi.setText("Zaustavi server");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        btnPokreni.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnPokreni.setText("Pokreni server");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPokreni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(btnZaustavi)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni)
                    .addComponent(btnZaustavi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        ps.interrupt();       
        serverNijePokrenut();

    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void btnPodavanjeBazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPodavanjeBazeActionPerformed
        // TODO add your handling code here:
        new FrmKonfiguracijaBaze().setVisible(true);

    }//GEN-LAST:event_btnPodavanjeBazeActionPerformed

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        // TODO add your handling code here:

        ps = new PokretanjeServera();
        ps.start();
        pokreniServer();

    }//GEN-LAST:event_btnPokreniActionPerformed

    /**
     * @param args the command line arguments
     */
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPodavanjeBaze;
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblServer;
    // End of variables declaration//GEN-END:variables

    public void pokreniServer() {
        lblServer.setText("Server je pokrenut!");
        btnPokreni.setEnabled(false);
        btnZaustavi.setEnabled(true);
        lblServer.setForeground(Color.GREEN);
    }

    public void serverNijePokrenut() {
        lblServer.setText("Server nije pokrenut!");
        btnPokreni.setEnabled(true);
        btnZaustavi.setEnabled(false);
        lblServer.setForeground(Color.red);
    }

    private void srediFormu() {
        setLocationRelativeTo(null);
        setTitle("BG Media");
        lblServer.setText("Server nije pokrenut!");
        lblServer.setForeground(Color.red);

    }
}
